"""
Small initial ticker/company universe for Joseph Carlson-style US equity portfolios.

You can expand this list after seeing which stocks appear in the videos.
Format:
    ("TICKER", "Company Name", ["Alias 1", "Alias 2"])
"""

TICKERS = [
    ("AAPL", "Apple", ["Apple stock", "Apple Inc", "iPhone"]),
    ("MSFT", "Microsoft", ["Microsoft stock", "Azure"]),
    ("GOOGL", "Alphabet", ["Google", "Alphabet stock", "Google stock"]),
    ("GOOG", "Alphabet", ["Google", "Alphabet stock", "Google stock"]),
    ("AMZN", "Amazon", ["Amazon stock", "AWS"]),
    ("META", "Meta Platforms", ["Meta", "Facebook", "Instagram"]),
    ("NVDA", "Nvidia", ["NVIDIA", "Nvidia stock"]),
    ("TSLA", "Tesla", ["Tesla stock"]),
    ("BRK.B", "Berkshire Hathaway", ["Berkshire", "Berkshire Hathaway", "Warren Buffett"]),
    ("BRK.A", "Berkshire Hathaway", ["Berkshire", "Berkshire Hathaway", "Warren Buffett"]),
    ("V", "Visa", ["Visa stock"]),
    ("MA", "Mastercard", ["Mastercard stock"]),
    ("PYPL", "PayPal", ["Paypal", "PayPal stock"]),
    ("ADBE", "Adobe", ["Adobe stock"]),
    ("CRM", "Salesforce", ["Salesforce stock"]),
    ("NFLX", "Netflix", ["Netflix stock"]),
    ("DIS", "Disney", ["Disney stock", "Walt Disney"]),
    ("SBUX", "Starbucks", ["Starbucks stock"]),
    ("COST", "Costco", ["Costco stock"]),
    ("WMT", "Walmart", ["Walmart stock"]),
    ("TGT", "Target", ["Target stock"]),
    ("HD", "Home Depot", ["Home Depot"]),
    ("LOW", "Lowe's", ["Lowes", "Lowe's"]),
    ("NKE", "Nike", ["Nike stock"]),
    ("MCD", "McDonald's", ["McDonalds", "McDonald's stock"]),
    ("KO", "Coca-Cola", ["Coca Cola", "Coke stock"]),
    ("PEP", "PepsiCo", ["Pepsi", "PepsiCo"]),
    ("JNJ", "Johnson & Johnson", ["Johnson and Johnson", "J&J"]),
    ("PG", "Procter & Gamble", ["Procter and Gamble", "P&G"]),
    ("UNH", "UnitedHealth", ["United Health", "UnitedHealth Group"]),
    ("ABBV", "AbbVie", ["Abbvie"]),
    ("LLY", "Eli Lilly", ["Eli Lilly"]),
    ("MRK", "Merck", ["Merck stock"]),
    ("PFE", "Pfizer", ["Pfizer stock"]),
    ("JPM", "JPMorgan Chase", ["JP Morgan", "JPMorgan"]),
    ("BAC", "Bank of America", ["Bank of America"]),
    ("WFC", "Wells Fargo", ["Wells Fargo"]),
    ("GS", "Goldman Sachs", ["Goldman"]),
    ("MS", "Morgan Stanley", ["Morgan Stanley"]),
    ("BLK", "BlackRock", ["BlackRock"]),
    ("SCHW", "Charles Schwab", ["Schwab", "Charles Schwab"]),
    ("TROW", "T. Rowe Price", ["T Rowe Price", "T. Rowe"]),
    ("O", "Realty Income", ["Realty Income"]),
    ("PLD", "Prologis", ["Prologis"]),
    ("AMT", "American Tower", ["American Tower"]),
    ("EQIX", "Equinix", ["Equinix"]),
    ("SPG", "Simon Property Group", ["Simon Property"]),
    ("INTC", "Intel", ["Intel stock"]),
    ("AMD", "Advanced Micro Devices", ["AMD stock", "Advanced Micro Devices"]),
    ("AVGO", "Broadcom", ["Broadcom"]),
    ("QCOM", "Qualcomm", ["Qualcomm"]),
    ("TXN", "Texas Instruments", ["Texas Instruments"]),
    ("CSCO", "Cisco", ["Cisco"]),
    ("ORCL", "Oracle", ["Oracle stock"]),
    ("IBM", "IBM", ["International Business Machines"]),
    ("NOW", "ServiceNow", ["ServiceNow"]),
    ("SHOP", "Shopify", ["Shopify"]),
    ("SQ", "Block", ["Square", "Block stock"]),
    ("COIN", "Coinbase", ["Coinbase"]),
    ("PLTR", "Palantir", ["Palantir"]),
    ("SNOW", "Snowflake", ["Snowflake"]),
    ("UBER", "Uber", ["Uber stock"]),
    ("ABNB", "Airbnb", ["Airbnb"]),
    ("RBLX", "Roblox", ["Roblox"]),
    ("ROKU", "Roku", ["Roku"]),
    ("ZM", "Zoom", ["Zoom Video"]),
    ("DOCU", "DocuSign", ["Docusign"]),
    ("SPOT", "Spotify", ["Spotify"]),
    ("BABA", "Alibaba", ["Alibaba"]),
    ("TCEHY", "Tencent", ["Tencent"]),
    ("NIO", "Nio", ["NIO stock"]),
    ("LI", "Li Auto", ["Li Auto"]),
    ("XPEV", "XPeng", ["Xpeng"]),
    ("RIVN", "Rivian", ["Rivian"]),
    ("LCID", "Lucid", ["Lucid Motors"]),
    ("F", "Ford", ["Ford stock", "Ford Motor"]),
    ("GM", "General Motors", ["General Motors"]),
    ("TM", "Toyota", ["Toyota"]),
    ("HMC", "Honda", ["Honda"]),
    ("XOM", "Exxon Mobil", ["Exxon", "ExxonMobil"]),
    ("CVX", "Chevron", ["Chevron"]),
    ("COP", "ConocoPhillips", ["Conoco"]),
    ("NEE", "NextEra Energy", ["NextEra"]),
    ("DUK", "Duke Energy", ["Duke Energy"]),
    ("SO", "Southern Company", ["Southern Company"]),
    ("BA", "Boeing", ["Boeing"]),
    ("LMT", "Lockheed Martin", ["Lockheed"]),
    ("RTX", "RTX", ["Raytheon", "RTX"]),
    ("CAT", "Caterpillar", ["Caterpillar"]),
    ("DE", "Deere", ["John Deere", "Deere"]),
    ("UPS", "UPS", ["United Parcel Service"]),
    ("FDX", "FedEx", ["Fedex"]),
    ("DHR", "Danaher", ["Danaher"]),
    ("TMO", "Thermo Fisher", ["Thermo Fisher"]),
    ("ISRG", "Intuitive Surgical", ["Intuitive Surgical"]),
    ("EL", "Estée Lauder", ["Estee Lauder", "Estée Lauder"]),
    ("LULU", "Lululemon", ["Lululemon"]),
    ("ELF", "e.l.f. Beauty", ["elf Beauty", "e.l.f."]),
    ("CELH", "Celsius", ["Celsius Holdings"]),
]
