"""
Asset universe used by the transcript extractor.

Broad enough for common finance YouTube channels, but still simple enough to edit.
The extractor only produces candidate rows. Important rows still need manual checks.
"""

TICKERS = [
    ("SPY", "S&P 500 proxy ETF", ["S&P 500", "SP500", "S and P 500", "S&P"]),
    ("QQQ", "Nasdaq 100 proxy ETF", ["Nasdaq", "Nasdaq 100", "NASDAQ", "QQQ"]),
    ("DIA", "Dow Jones proxy ETF", ["Dow Jones", "Dow"]),
    ("IWM", "Russell 2000 proxy ETF", ["Russell 2000", "small caps", "small cap index"]),
    ("EWG", "Germany equity proxy ETF", ["DAX", "Deutscher Aktienindex", "Germany index"]),
    ("FEZ", "Euro Stoxx 50 proxy ETF", ["Euro Stoxx", "Euro Stoxx 50", "Stoxx 50"]),
    ("GLD", "Gold proxy ETF", ["Gold", "Goldpreis", "XAU", "XAUUSD"]),
    ("SLV", "Silver proxy ETF", ["Silver", "Silber", "Silberpreis", "XAG", "XAGUSD"]),
    ("USO", "Oil proxy ETF", ["Oil", "Crude oil", "WTI", "Brent", "Oel"]),

    ("BTC-USD", "Bitcoin", ["Bitcoin", "BTC", "Bitcoin Kurs"]),
    ("ETH-USD", "Ethereum", ["Ethereum", "Ether", "ETH"]),
    ("SOL-USD", "Solana", ["Solana", "SOL"]),
    ("XRP-USD", "XRP", ["XRP", "Ripple"]),
    ("ADA-USD", "Cardano", ["Cardano", "ADA"]),
    ("BNB-USD", "BNB", ["BNB", "Binance Coin"]),
    ("DOGE-USD", "Dogecoin", ["Dogecoin", "DOGE"]),
    ("AVAX-USD", "Avalanche", ["Avalanche", "AVAX"]),
    ("LINK-USD", "Chainlink", ["Chainlink", "LINK"]),
    ("DOT-USD", "Polkadot", ["Polkadot", "DOT"]),
    ("MATIC-USD", "Polygon", ["Polygon", "Matic", "MATIC"]),
    ("LTC-USD", "Litecoin", ["Litecoin", "LTC"]),
    ("BCH-USD", "Bitcoin Cash", ["Bitcoin Cash", "BCH"]),
    ("ATOM-USD", "Cosmos", ["Cosmos", "ATOM"]),
    ("NEAR-USD", "Near Protocol", ["Near Protocol", "NEAR"]),
    ("ICP-USD", "Internet Computer", ["ICP", "Internet Computer"]),
    ("AAVE-USD", "Aave", ["Aave", "AAVE"]),
    ("UNI-USD", "Uniswap", ["Uniswap", "UNI"]),
    ("XLM-USD", "Stellar", ["Stellar", "XLM"]),
    ("ARB-USD", "Arbitrum", ["Arbitrum", "ARB"]),
    ("OP-USD", "Optimism", ["Optimism", "OP"]),
    ("INJ-USD", "Injective", ["Injective", "INJ"]),
    ("RENDER-USD", "Render", ["Render", "RNDR", "RENDER"]),

    ("AAPL", "Apple", ["Apple stock", "Apple Inc", "iPhone"]),
    ("MSFT", "Microsoft", ["Microsoft stock", "Azure"]),
    ("GOOGL", "Alphabet", ["Google", "Alphabet stock", "Google stock"]),
    ("AMZN", "Amazon", ["Amazon stock", "AWS"]),
    ("META", "Meta Platforms", ["Meta", "Facebook", "Instagram"]),
    ("NVDA", "Nvidia", ["NVIDIA", "Nvidia stock"]),
    ("TSLA", "Tesla", ["Tesla stock"]),
    ("BRK-B", "Berkshire Hathaway", ["Berkshire", "Berkshire Hathaway", "Warren Buffett"]),
    ("V", "Visa", ["Visa stock"]),
    ("MA", "Mastercard", ["Mastercard stock"]),
    ("PYPL", "PayPal", ["Paypal", "PayPal stock"]),
    ("ADBE", "Adobe", ["Adobe stock"]),
    ("CRM", "Salesforce", ["Salesforce stock"]),
    ("NFLX", "Netflix", ["Netflix stock"]),
    ("DIS", "Disney", ["Disney stock", "Walt Disney"]),
    ("SBUX", "Starbucks", ["Starbucks stock"]),
    ("COST", "Costco", ["Costco stock"]),
    ("WMT", "Walmart", ["Walmart stock"]),
    ("TGT", "Target", ["Target stock"]),
    ("HD", "Home Depot", ["Home Depot"]),
    ("LOW", "Lowe's", ["Lowes", "Lowe's"]),
    ("NKE", "Nike", ["Nike stock"]),
    ("MCD", "McDonald's", ["McDonalds", "McDonald's stock"]),
    ("KO", "Coca-Cola", ["Coca Cola", "Coke stock"]),
    ("PEP", "PepsiCo", ["Pepsi", "PepsiCo"]),
    ("JNJ", "Johnson & Johnson", ["Johnson and Johnson", "J&J"]),
    ("PG", "Procter & Gamble", ["Procter and Gamble", "P&G"]),
    ("UNH", "UnitedHealth", ["United Health", "UnitedHealth Group"]),
    ("ABBV", "AbbVie", ["Abbvie"]),
    ("LLY", "Eli Lilly", ["Eli Lilly"]),
    ("MRK", "Merck", ["Merck stock"]),
    ("PFE", "Pfizer", ["Pfizer stock"]),
    ("JPM", "JPMorgan Chase", ["JP Morgan", "JPMorgan"]),
    ("BAC", "Bank of America", ["Bank of America"]),
    ("WFC", "Wells Fargo", ["Wells Fargo"]),
    ("GS", "Goldman Sachs", ["Goldman"]),
    ("MS", "Morgan Stanley", ["Morgan Stanley"]),
    ("BLK", "BlackRock", ["BlackRock"]),
    ("SCHW", "Charles Schwab", ["Schwab", "Charles Schwab"]),
    ("TROW", "T. Rowe Price", ["T Rowe Price", "T. Rowe"]),
    ("O", "Realty Income", ["Realty Income"]),
    ("PLD", "Prologis", ["Prologis"]),
    ("AMT", "American Tower", ["American Tower"]),
    ("EQIX", "Equinix", ["Equinix"]),
    ("SPG", "Simon Property Group", ["Simon Property"]),

    ("INTC", "Intel", ["Intel stock"]),
    ("AMD", "Advanced Micro Devices", ["AMD stock", "Advanced Micro Devices"]),
    ("AVGO", "Broadcom", ["Broadcom"]),
    ("QCOM", "Qualcomm", ["Qualcomm"]),
    ("TXN", "Texas Instruments", ["Texas Instruments"]),
    ("CSCO", "Cisco", ["Cisco"]),
    ("ORCL", "Oracle", ["Oracle stock"]),
    ("IBM", "IBM", ["International Business Machines"]),
    ("NOW", "ServiceNow", ["ServiceNow"]),
    ("SHOP", "Shopify", ["Shopify"]),
    ("SQ", "Block", ["Square", "Block stock"]),
    ("COIN", "Coinbase", ["Coinbase"]),
    ("PLTR", "Palantir", ["Palantir"]),
    ("SNOW", "Snowflake", ["Snowflake"]),
    ("UBER", "Uber", ["Uber stock"]),
    ("ABNB", "Airbnb", ["Airbnb"]),
    ("RBLX", "Roblox", ["Roblox"]),
    ("ROKU", "Roku", ["Roku"]),
    ("ZM", "Zoom", ["Zoom Video"]),
    ("DOCU", "DocuSign", ["Docusign"]),
    ("SPOT", "Spotify", ["Spotify"]),
    ("SOFI", "SoFi Technologies", ["SoFi", "SoFi stock"]),
    ("HIMS", "Hims & Hers Health", ["Hims and Hers", "Hims & Hers", "Hims"]),
    ("RKLB", "Rocket Lab", ["Rocket Lab"]),
    ("HOOD", "Robinhood", ["Robinhood"]),
    ("MELI", "MercadoLibre", ["Mercado Libre", "MercadoLibre"]),
    ("NU", "Nu Holdings", ["Nu Holdings", "Nubank"]),

    ("BABA", "Alibaba", ["Alibaba"]),
    ("TCEHY", "Tencent", ["Tencent"]),
    ("NIO", "Nio", ["NIO stock"]),
    ("LI", "Li Auto", ["Li Auto"]),
    ("XPEV", "XPeng", ["Xpeng"]),
    ("ASML", "ASML", ["ASML"]),
    ("SAP", "SAP", ["SAP stock"]),
    ("SIE.DE", "Siemens", ["Siemens"]),
    ("ALV.DE", "Allianz", ["Allianz"]),
    ("DTE.DE", "Deutsche Telekom", ["Deutsche Telekom", "Telekom"]),
    ("MBG.DE", "Mercedes-Benz Group", ["Mercedes", "Mercedes Benz"]),
    ("BMW.DE", "BMW", ["BMW"]),
    ("VOW3.DE", "Volkswagen", ["Volkswagen", "VW"]),
    ("BAYN.DE", "Bayer", ["Bayer"]),
    ("AIR.PA", "Airbus", ["Airbus"]),
    ("MC.PA", "LVMH", ["LVMH", "Louis Vuitton"]),
    ("NESN.SW", "Nestle", ["Nestle"]),
    ("NOVN.SW", "Novartis", ["Novartis"]),
    ("ROG.SW", "Roche", ["Roche"]),

    ("RIVN", "Rivian", ["Rivian"]),
    ("LCID", "Lucid", ["Lucid Motors"]),
    ("F", "Ford", ["Ford stock", "Ford Motor"]),
    ("GM", "General Motors", ["General Motors"]),
    ("TM", "Toyota", ["Toyota"]),
    ("HMC", "Honda", ["Honda"]),
    ("XOM", "Exxon Mobil", ["Exxon", "ExxonMobil"]),
    ("CVX", "Chevron", ["Chevron"]),
    ("COP", "ConocoPhillips", ["Conoco"]),
    ("NEE", "NextEra Energy", ["NextEra"]),
    ("DUK", "Duke Energy", ["Duke Energy"]),
    ("SO", "Southern Company", ["Southern Company"]),
    ("BA", "Boeing", ["Boeing"]),
    ("LMT", "Lockheed Martin", ["Lockheed"]),
    ("RTX", "RTX", ["Raytheon", "RTX"]),
    ("CAT", "Caterpillar", ["Caterpillar"]),
    ("DE", "Deere", ["John Deere", "Deere"]),
    ("UPS", "UPS", ["United Parcel Service"]),
    ("FDX", "FedEx", ["Fedex"]),
    ("DHR", "Danaher", ["Danaher"]),
    ("TMO", "Thermo Fisher", ["Thermo Fisher"]),
    ("ISRG", "Intuitive Surgical", ["Intuitive Surgical"]),
    ("EL", "Estee Lauder", ["Estee Lauder"]),
    ("LULU", "Lululemon", ["Lululemon"]),
    ("ELF", "e.l.f. Beauty", ["elf Beauty", "e.l.f."]),
    ("CELH", "Celsius", ["Celsius Holdings"]),
]
